/**
 * Application Constants
 * Centralized constants to avoid magic numbers and strings
 */

// HTTP Status Codes
const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
};

// Pagination Defaults
const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100,
  MIN_LIMIT: 1,
};

// Order Status
const ORDER_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  PROCESSING: 'PROCESSING',
  READY_FOR_DELIVERY: 'READY_FOR_DELIVERY',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

// Order Status Transitions
const ORDER_STATUS_TRANSITIONS = {
  [ORDER_STATUS.PENDING]: [ORDER_STATUS.CONFIRMED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.CONFIRMED]: [ORDER_STATUS.PROCESSING, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.PROCESSING]: [ORDER_STATUS.READY_FOR_DELIVERY, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.READY_FOR_DELIVERY]: [ORDER_STATUS.OUT_FOR_DELIVERY, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.OUT_FOR_DELIVERY]: [ORDER_STATUS.DELIVERED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.DELIVERED]: [ORDER_STATUS.COMPLETED],
  [ORDER_STATUS.CANCELLED]: [],
  [ORDER_STATUS.COMPLETED]: [],
};

// Cancellable Order Statuses
const CANCELLABLE_ORDER_STATUSES = [
  ORDER_STATUS.PENDING,
  ORDER_STATUS.CONFIRMED,
  ORDER_STATUS.PROCESSING,
];

// User Roles
const USER_ROLES = {
  ADMIN: 'ADMIN',
  OPERATOR: 'OPERATOR',
  RETAILER: 'RETAILER',
  WHOLESALER: 'WHOLESALER',
};

// Admin Roles (can access all resources)
const ADMIN_ROLES = [USER_ROLES.ADMIN, USER_ROLES.OPERATOR];

// Uploaded Order Status
const UPLOADED_ORDER_STATUS = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  PENDING_REVIEW: 'PENDING_REVIEW',
};

// File Upload Limits
const FILE_UPLOAD = {
  MAX_SIZE_MB: 10,
  MAX_SIZE_BYTES: 10 * 1024 * 1024,
  ALLOWED_IMAGE_TYPES: ['image/jpeg', 'image/jpg', 'image/png', 'image/webp'],
};

// OCR Configuration
const OCR_CONFIG = {
  MIN_CONFIDENCE: 0.5,
  DEFAULT_CONFIDENCE: 0.5,
  HIGH_CONFIDENCE: 0.8,
};

// LLM Configuration
const LLM_CONFIG = {
  TEMPERATURE: 0.1,
  TIMEOUT_MS: 30000,
  MIN_CONFIDENCE: 0.5,
  DEFAULT_CONFIDENCE: 0.5,
};

// Product Matching
const PRODUCT_MATCHING = {
  MIN_CONFIDENCE: 0.7,
  HIGH_CONFIDENCE: 0.85,
  EXACT_MATCH_CONFIDENCE: 1.0,
};

// Wholesaler Ranking Weights
const RANKING_WEIGHTS = {
  RELIABILITY: 0.4,
  PRICE: 0.3,
  FULFILLMENT: 0.2,
  RESPONSE: 0.1,
};

// Supplier Allocation Weights
const ALLOCATION_WEIGHTS = {
  COST: 0.7,
  RELIABILITY: 0.3,
};

// Order Number Format
const ORDER_NUMBER = {
  PREFIX: 'ORD',
  SEQUENCE_LENGTH: 4,
  DATE_FORMAT: 'YYMMDD',
};

// Signed URL Expiration
const SIGNED_URL = {
  DEFAULT_EXPIRATION_MINUTES: 60,
  SHORT_EXPIRATION_MINUTES: 15,
  LONG_EXPIRATION_MINUTES: 240,
};

// Queue Configuration
const QUEUE_CONFIG = {
  DEFAULT_ATTEMPTS: 3,
  EXPONENTIAL_BACKOFF_DELAY_MS: 5000,
  MAX_COMPLETED_JOBS: 100,
  REMOVE_ON_COMPLETE: true,
  REMOVE_ON_FAIL: false,
};

// Retry Configuration
const RETRY_CONFIG = {
  MAX_ATTEMPTS: 3,
  INITIAL_DELAY_MS: 1000,
  MAX_DELAY_MS: 10000,
  BACKOFF_MULTIPLIER: 2,
};

// Time Constants
const TIME = {
  ONE_SECOND_MS: 1000,
  ONE_MINUTE_MS: 60 * 1000,
  ONE_HOUR_MS: 60 * 60 * 1000,
  ONE_DAY_MS: 24 * 60 * 60 * 1000,
};

// Database Query Limits
const DB_LIMITS = {
  MAX_BATCH_SIZE: 1000,
  DEFAULT_TAKE: 20,
  MAX_TAKE: 100,
};

// Error Codes
const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  CONFLICT: 'CONFLICT',
  BUSINESS_LOGIC_ERROR: 'BUSINESS_LOGIC_ERROR',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
};

// Log Levels
const LOG_LEVELS = {
  ERROR: 'error',
  WARN: 'warn',
  INFO: 'info',
  DEBUG: 'debug',
};

module.exports = {
  HTTP_STATUS,
  PAGINATION,
  ORDER_STATUS,
  ORDER_STATUS_TRANSITIONS,
  CANCELLABLE_ORDER_STATUSES,
  USER_ROLES,
  ADMIN_ROLES,
  UPLOADED_ORDER_STATUS,
  FILE_UPLOAD,
  OCR_CONFIG,
  LLM_CONFIG,
  PRODUCT_MATCHING,
  RANKING_WEIGHTS,
  ALLOCATION_WEIGHTS,
  ORDER_NUMBER,
  SIGNED_URL,
  QUEUE_CONFIG,
  RETRY_CONFIG,
  TIME,
  DB_LIMITS,
  ERROR_CODES,
  LOG_LEVELS,
};
